Add fromItemMultiplier & fromBookMultiplier
PrismarineJS/minecraft-data pull request #366
Opened 2021-02-22 04:26 UTC by u9g

2021-02-22 08:27 UTC, rom1504 requested changes
Can you put these js files in an extractor repo instead ?

2021-02-22 12:57 UTC, u9g commented
> Can you put these js files in an extractor repo instead ?

done https://github.com/u9g/enchant-multiplier-injector/tree/main

2021-02-22 14:39 UTC, Karang approved these changes

2021-02-22 14:40 UTC, merged

2021-02-24 07:59 UTC, rom1504 commented
Same comment there, add a link to that extractor to https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md (and also to the table in the readme)